baseurl: "https://gcp-resume-challenge.alfonsmr.com/"
title: A Cloud Guru GCP Resume Challenge
theme: ghostwriter
languageCode: en
copyright: Alfons Muñoz
disqusShortname: XXX
googleAnalytics: XXX
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: My Name
  profile: ""

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: GCP Resume Challenge
  description: Challenge Designed by @MattiasEh. Implemented by @alfons_mr
  github: "https://github.com/alfonsmr"
  #gitlab: "https://gitlab.com/XXX"
  linkedin: "https://linkedin.com/in/alfonsmr/"
  twitter: "https://twitter.com/alfons_mr"
  stackoverflow: "https://stackoverflow.com/users/14301484/alfons-muñoz"
  facebook: "https://www.facebook.com/aristaequisTD"
  email: alfons.munoz@aristaequis.com
  opengraph: true
  shareTwitter: true
  rss: false
  shareFacebook: true
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  # If you want to use plausible(https://plausible.io) for analytics, add this section
  plausibleAnalytics:
    domain: ""
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL: ""

permalinks:
  post: "/:year/:month/:day/:filename/"

menu:
  main:
    - name: Projects
      url: /project/acloudguru-gcp-resume-challenge/
      weight: 1
